# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\daa_ui1.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1300, 900)
        Form.setMinimumSize(QtCore.QSize(1300, 900))
        Form.setMaximumSize(QtCore.QSize(1300, 900))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 861, 896))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(740, 80, 100, 671))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("UI\pic/alt.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(750, 420, 21, 321))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("UI\pic/编组 6.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 130, 600, 600))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("UI\pic/1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 100, 671))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("UI\pic/编组 7.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(20, 530, 21, 211))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("UI\pic/编组 6.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(385, 50, 72, 681))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("UI\pic/其他.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(600, 760, 261, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(600, 800, 261, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(600, 840, 261, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 800, 501, 61))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(870, 0, 421, 485))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 141, 41))
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setPixmap(QtGui.QPixmap("UI\pic/7.png"))
        self.label_5.setObjectName("label_5")
        self.label_33 = QtWidgets.QLabel(self.frame_2)
        self.label_33.setGeometry(QtCore.QRect(20, 70, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        self.label_34.setGeometry(QtCore.QRect(20, 270, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(870, 495, 421, 401))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.label_18.setObjectName("label_18")
        self.layoutWidget4 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 200, 20, 87))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-1.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_3.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-2.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_3.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-3.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_3.addWidget(self.label_29)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 300, 20, 87))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-1.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_4.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-2.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_4.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-3.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_4.addWidget(self.label_32)
        self.layoutWidget5 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 100, 20, 87))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-1.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-2.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("UI\pic/Rectangle-3.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.layoutWidget6 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(370, 100, 31, 291))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("UI\pic/编组 4.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("UI\pic/编组 8.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("UI\pic\编组 8-2.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("UI\pic/编组 8-3.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("UI\pic/编组 5.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.layoutWidget7 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget7.setGeometry(QtCore.QRect(230, 20, 179, 26))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget7)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setMaxVisibleItems(4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_2)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_5.addWidget(self.label_35)
        self.layoutWidget8 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 20, 215, 26))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget8)
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_6.addWidget(self.label_36)
        self.layoutWidget9 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget9.setGeometry(QtCore.QRect(110, 100, 251, 291))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line = QtWidgets.QFrame(self.layoutWidget9)
        self.line.setStyleSheet("color:rgb(170, 0, 0)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_3.setStyleSheet("color:rgb(0, 170, 0)")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_4 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_5.setStyleSheet("color:rgb(170, 0, 0)")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_6.setStyleSheet("color:rgb(0, 0, 255)")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_6.addWidget(self.line_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_7 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_7.setStyleSheet("color:rgb(255, 255, 255)")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_8.setStyleSheet("color:rgb(0, 85, 0)")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_7.addWidget(self.line_8)
        self.line_9 = QtWidgets.QFrame(self.layoutWidget9)
        self.line_9.setStyleSheet("color:rgb(170, 0, 0)")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_7.addWidget(self.line_9)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.layoutWidget10 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget10.setGeometry(QtCore.QRect(50, 103, 45, 281))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_8.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_8.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_8.addWidget(self.label_39)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_9.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_9.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_9.addWidget(self.label_42)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_11.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_11.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_11.addWidget(self.label_45)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)

        self.retranslateUi(Form)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DAA_UI1"))
        self.label_4.setText(_translate("Form", "ALT"))
        self.label_16.setText(_translate("Form", "TESTALT"))
        self.label_6.setText(_translate("Form", "TCAS SPEED"))
        self.label_17.setText(_translate("Form", "TEST TCAS"))
        self.label_7.setText(_translate("Form", "GS"))
        self.label_22.setText(_translate("Form", "TEST GS"))
        self.label_8.setText(_translate("Form", "Longitude/Latitude "))
        self.label_13.setText(_translate("Form", "TEST LONLAT"))
        self.label_33.setText(_translate("Form", "Location"))
        self.label_34.setText(_translate("Form", "Speed"))
        self.label_18.setText(_translate("Form", "FLIGHT LEVEL LIST"))
        self.label_14.setText(_translate("Form", "VERTICAL"))
        self.comboBox_2.setCurrentText(_translate("Form", "8000"))
        self.comboBox_2.setItemText(0, _translate("Form", "8000"))
        self.label_35.setText(_translate("Form", "FT"))
        self.label_12.setText(_translate("Form", "ALONG TRACK     "))
        self.comboBox.setCurrentText(_translate("Form", "50"))
        self.comboBox.setItemText(0, _translate("Form", "50"))
        self.label_36.setText(_translate("Form", "NM"))
        self.label_37.setText(_translate("Form", "FL8000"))
        self.label_38.setText(_translate("Form", "FL8200"))
        self.label_39.setText(_translate("Form", "FL8400"))
        self.label_40.setText(_translate("Form", "FL8600"))
        self.label_41.setText(_translate("Form", "FL8800"))
        self.label_42.setText(_translate("Form", "FL9000"))
        self.label_43.setText(_translate("Form", "FL9200"))
        self.label_44.setText(_translate("Form", "FL9400"))
        self.label_45.setText(_translate("Form", "FL9600"))
